version: "3"
services:
  zerto_stats2_poller:
    build:
      context: .
      dockerfile: poller/dockerfile
    container_name: zerto_stats2_poller
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - zerto_stats2_poller:/zerto_stats2
      
volumes:
  zerto_stats2_poller:
