FROM alpine:latest
RUN apk add python3
RUN apk add py3-pip
COPY . /zerto_stats2
WORKDIR /zerto_stats2
RUN pip install -r requirements.txt
RUN pip install --upgrade pip
WORKDIR /zerto_stats2/poller
ENTRYPOINT ["python3"]
CMD ["run.py"]